import type { Metadata } from "next";
import { Geist, Geist_Mono, Trocchi } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import NavbarComponent from "@/components/NavBar";
import GridPatternBackground from "@/components/ui/grid-pattern-background";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const trocchi = Trocchi({
  variable: "--font-trocchi",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "prtk - Data Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="dark"
      style={{ colorScheme: "dark" }}
    >
      <body
        className={`${trocchi.variable} ${geistMono.variable} antialiased relative`}
      >
        <GridPatternBackground
          className="pointer-events-none fixed inset-0 z-0"
          gridType="lines"
          gridSize={16}
          opacity={0.1}
          animate={false}
        />
        <Providers>
          <div className="relative z-10">
            <NavbarComponent />
            {children}
          </div>
        </Providers>
        <script
    src="https://cdn.databuddy.cc/databuddy.js"
    data-client-id="-WfdBGCX0UChXhO5Z-tqm"
    data-enable-batching="true"
    crossOrigin="anonymous"
    async
  ></script>
      </body>
    </html>
  );
}
