import type { Metadata } from "next";
import { Geist, Geist_Mono, Trocchi } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import NavbarComponent from "@/components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const trocchi = Trocchi({
  variable: "--font-trocchi",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "prtk - Data Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="dark"
      style={{ colorScheme: "dark" }}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <NavbarComponent />
          {children}
        </Providers>
        <script
    src="https://cdn.databuddy.cc/databuddy.js"
    data-client-id="-WfdBGCX0UChXhO5Z-tqm"
    data-enable-batching="true"
    crossOrigin="anonymous"
    async
  ></script>
      </body>
    </html>
  );
}
